language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"      # current default Python on Travis CI
  - "3.7"
  - "3.8"

install:
  - pip install nose==1.3.7 flake8==3.6.0 iso3166==1.0.1 -rrequirements.txt

script:
  - flake8 config_precedence
  - flake8 tests
  - nosetests \
      -sxv \
      --with-coverage \
      --cover-package=config_precedence
